rteval: Correct Python version in doc/rteval.txt
doc/rteval.txt specifies that rteval is a Python 2.x program. This is
not true, since rteval no longer works with Python 2.x:
$ python2 rteval-cmd
  File "rteval-cmd", line 67
    print(f"Don't know how to summarize {repfile} (tarfile open failed)")
                                                                       ^
SyntaxError: invalid syntax

Replace "Python 2.x" with "Python 3.x".

Signed-off-by: Tomas Glozar <tglozar@redhat.com>
Signed-off-by: John Kacur <jkacur@redhat.com>