rteval: Don't attempt to get DMIinfo if there are dmi warnings
If the python module dmidecode is available, but produces warnings,
you can get a traceback. This happens on some arm boxes,
as shown in the traceback below.

Fix this by treating any warnings that are not listed in the
ignorable warnings as if dmi info is not available.

Also add logging to dmi.ProcessWarnings()

./rteval-cmd -d10s
** DMI WARNING ** /sys/firmware/efi/systab: SMBIOS entry point missing
got system topology: 1 node system (4 cores per node)
rteval run on 5.19.16-200.fc36.aarch64 started at Fri Oct 21 16:11:51 2022
started 3 loads on 4 cores
started measurement threads on 4 cores
Run duration: 10.0 seconds
stopping run at Fri Oct 21 16:13:26 2022
Traceback (most recent call last):
  File "/root/src/rteval/./rteval-cmd", line 402, in <module>
    ec = rteval.Measure()
  File "/root/src/rteval/rteval/__init__.py", line 286, in Measure
    self._report(measure_start, self.__rtevcfg.xslt_report)
  File "/root/src/rteval/rteval/rtevalReport.py", line 76, in _report
    self.__xmlreport.AppendXMLnodes(self._sysinfo.MakeReport())
  File "/root/src/rteval/rteval/sysinfo/__init__.py", line 69, in MakeReport
    report_n.addChild(dmi.DMIinfo.MakeReport(self))
  File "/root/src/rteval/rteval/sysinfo/dmi.py", line 111, in MakeReport
    dmiqry = xmlout.convert_libxml2_to_lxml_doc(self.__dmixml.QuerySection('all'))
  File "/usr/lib64/python3.10/site-packages/dmidecode.py", line 64, in QuerySection
    ret = libxml2.xmlDoc( _obj = xmlapi(query_type='s',
RuntimeError: [src/dmidecodemodule.c:331] Error decoding DMI data

** COLLECTED WARNINGS **
/sys/firmware/efi/systab: SMBIOS entry point missing
** END OF WARNINGS **

Signed-off-by: John Kacur <jkacur@redhat.com>